---
###################################################################################################################
# Validation IaC Configuration State.
###################################################################################################################
  - name: Windows - Validating the Underlaying IaC...
    win_stat:
      path: 'C:\techdata-iac\windows-packet{{PACKET_NAME}}-is-installed.md'
    register: agent_status_is
  - debug: var=agent_status_is

  # Download the CrowdStrike agent for Windows
  - name: Windows - Installer Packet from Remote Location.
    win_get_url:
      force: True
      validate_certs: False #SSL certificates will not be validated.
      url: "{{REMOTE_SOURCE_PACKET_INSTALLER}}" # Full URL to download from.
      dest: C:\techdata-iac\  # Path to download to.
      proxy_url: "{{HTTP_PROXY}}"
    register: iac_status_is
    when: agent_status_is.stat.exists == false
  - debug: var=iac_status_is
    tags: download_windows_agent

  # Install the downloaded CrowdStrike package
  - name: "Windows - Installing {{ PACKET_NAME }} ..."
    win_package:
      path: 'C:\techdata-iac\{{PACKET_NAME}}'
      state: present
      product_id: "{{PACKET_INSTALLER_PID}}"
      log_path: C:\techdata-iac\install-log-{{PACKET_NAME}}-{{lookup('pipe', 'date +%Y%m%dT%H%M%S')}}.log
    register: iac_status_is
    when: agent_status_is.stat.exists == false
    tags: install_windows_agent
  - debug: var=iac_status_is

  - name: Windows - Cleanup Temporal Installer.
    win_file:
      path: 'C:\techdata-iac\{{PACKET_NAME}}'
      state: absent
    register: iac_status_is
    when: agent_status_is.stat.exists == false
  - debug: var=iac_status_is

  - name: Windows - Registrying IaC Configuration DataStore.
    win_file:
      path: C:\techdata-iac
      state: directory
    register: iac_directory_is
    when: agent_status_is.stat.exists == false
  - debug: var=iac_directory_is

  - name: Windows - Set IaC Control Flag on Windows Host.
    win_file:
      path: 'C:\techdata-iac\windows-packet{{PACKET_NAME}}-is-installed.md'
      state: touch
    register: iac_directory_is
    when: agent_status_is.stat.exists == false
  - debug: var=iac_directory_is

    

